Cast mimetype to lang-appropriate str type.
Fixes https://issuetracker.google.com/issues/136688879. This line will
fail in Python 3 if mime_type is a `bytes` object:

    if '/' not in mime_type:

with this error:

    TypeError: a bytes-like object is required, not 'str'